let prompts = [
    "Never have I ever slept on the floor.",
    "Never have I ever slept on the floor.",
    "Never have I ever traveled alone.",
    "Never have I ever broken someone’s nose.",
    "Never have I ever got lost in a mall.",
    "Never have I ever wet myself in public.",
    "Never have I ever fallen off the bed.",
    "Never have I ever told a secret in a family dinner.",
    "Never have I ever caused a fight, only to then just watch it from afar.",
    "Never have I ever stolen something.",
    "Never have I ever farted in an airplane.",
    "Never have I ever quit a job on the first day.",
    "Never have I ever walked barefoot on the streets.",
    "Never have I ever broken something in a friend’s house.",
    "Never have I ever botched a job interview.",
    "Never have I ever documented every single detail of a day on social media.",
    "Never have I ever lied to my parents.",
    "Never have I ever taken drugs.",
    "Never have I ever gone commando.",
    "Never have I ever jumped in the pool fully dressed.",
    "Never have I ever mistakenly bumped a baby’s head.",
    "Never have I ever had more than one partner at a time.",
    "Never have I ever had a rage fit.",
    "Never have I ever spent money that wasn’t mine.",
    "Never have I ever read a full book in one day.",
    "Never have I ever driven without a license.",
    "Never have I ever pretended to be someone’s friend to help them out of an awkward or dangerous situation.",
    "Never have I ever kissed someone in public.",
    "Never have I ever peed in the pool, with people nearby.",
    "Never have I ever made a phone or video call while flying in an airplane.",
    "Never have I ever had a stalker.",
    "Never have I ever eaten food in bed.",
    "Never have I ever gone to a concert alone.",
    "Never have I ever forgot someone’s name, just after asking it a second time.",
    "Never have I ever sold used items online.",
    "Never have I ever paid a gym subscription without actually using it.",
    "Never have I ever gossiped about someone as soon as they left.",
    "Never have I ever been on a flight for more than 12 hours.",
    "Never have I ever got fired from a job.",
    "Never have I ever gone to cinema alone.",
    "Never have I ever learned a new language.",
    "Never have I ever got a tattoo I’ve never told anyone about.",
    "Never have I ever broken up with a partner the same day we got together.",
    "Never have I ever eaten raw chicken.",
    "Never have I ever kissed someone under the rain.",
    "Never have I ever had more than 5 pets at any given time.",
    "Never have I ever visited Roman temples.",
    "Never have I ever slept completely naked.",
    "Never have I ever vomited in public.",
    "Never have I ever caused a fire.",
    "Never have I ever seen a total or anular solar eclipse.",
    "Never have I ever interrupted my boss in a work meeting.",
    "Never have I ever traveled on a train.",
    "Never have I ever collected a set of Panini stickers in an album.",
    "Never have I ever screamed in public.",
    "Never have I ever worked freelance jobs.",
    "Never have I ever got lost in a foreign city, without speaking the local language.",
    "Never have I ever created a false account on social media, then to actively keep using it.",
    "Never have I ever ran over an animal while driving.",
    "Never have I ever camped in the middle of the woods.",
    "Never have I ever ghosted a partner completely.",
    "Never have I ever sneezed underwater.",
    "Never have I ever been slapped in the face.",
    "Never have I ever eaten exotic food.",
    "Never have I ever hurt my best friend’s feelings.",
    "Never have I ever given a pet for adoption.",
    "Never have I ever bought unnecessary items, just for the discount.",
    "Never have I ever felt an earthquake.",
    "Never have I ever ran out of gas in the middle of nowhere.",
    "Never have I ever got banned from a specific store or location.",
    "Never have I ever done the position of this number.",
    "Never have I ever been assaulted or robbed.",
    "Never have I ever visited more than 5 countries.",
    "Never have I ever cried in the bathroom at work.",
    "Never have I ever mixed white and colored clothes while doing laundry, causing it all to get tainted.",
    "Never have I ever fought with a sibling.",
    "Never have I ever found money on the street, and kept it.",
    "Never have I ever seen a lunar eclipse.",
    "Never have I ever accidentally killed a pet.",
    "Never have I ever slept in a tent.",
    "Never have I ever been in a sand storm.",
    "Never have I ever worn clothes from a thrift shop.",
    "Never have I ever caused a big loss for the company I work for.",
    "Never have I ever had two separate cellphone numbers, for different purposes.",
    "Never have I ever regretted a tattoo shortly after doing it.",
    "Never have I ever unknowingly insulted a foreigner while traveling, with a gesture or a bad translation.",
    "Never have I ever broken a bone in my body.",
    "Never have I ever been trapped in an elevator for more than an hour.",
    "Never have I ever booked a fancy hotel suite.",
    "Never have I ever played paintball.",
    "Never have I ever gone hunting.",
    "Never have I ever got COVID-19.",
    "Never have I ever witnessed an erupting volcano.",
    "Never have I ever been in a limousine.",
    "Never have I ever kissed someone with my eyes open.",
    "Never have I ever sneaked into a party I wasn’t invited to.",
    "Never have I ever lost a connecting flight during a layover.",
    "Never have I ever noticed I’ve been lied to, but acted as if I didn’t.",
    "Never have I ever fell asleep while driving.",
    "Never have I ever collected a set of Pokémon cards.",
    "Never have I ever spilled wine on expensive furniture at someone’s house.",
    "Never have I ever accepted help from a complete stranger.",
    "Never have I ever had baby pee on me.",
    "Never have I ever traveled on a bus.",
    "Never have I ever been kidnapped.",
    "Never have I ever been cheated on more than once by the same partner.",
    "Never have I ever learned to do a new recipe during the pandemic.",
    "Never have I ever got a piercing I’ve never told anyone about.",
    "Never have I ever had an animal chase after me.",
    "Never have I ever donated to a charity.",
    "Never have I ever lied during a job interview.",
    "Never have I ever done a TikTok dance.",
    "Never have I ever been the only person watching a movie at the cinema.",
    "Never have I ever dropped my pants in public.",
    "Never have I ever gone to an Escape Room.",
    "Never have I ever done a 10-hour movie marathon in one day.",
    "Never have I ever written a poem.",
    "Never have I ever lied to my best friend.",
    "Never have I ever had stitches from an injury.",
    "Never have I ever loved and hated the same person.",
    "Never have I ever been in a snow storm.",
    "Never have I ever mixed salty and sweet popcorn.",
    "Never have I ever thought of hurting myself.",
    "Never have I ever catfished someone.",
    "Never have I ever fallen asleep while taking public transportation.",
    "Never have I ever bought more books, knowing I will never read them all.",
    "Never have I ever peed in the shower.",
    "Never have I ever walked and bumped into a glass door.",
    "Never have I ever cheated on an exam.",
    "Never have I ever been in a car accident.",
    "Never have I ever eaten food off of someone’s body.",
    "Never have I ever completely change university majors halfway through.",
    "Never have I ever fell asleep in the shower.",
    "Never have I ever slept in an airport.",
    "Never have I ever gone to a place just for the sake of taking a specific photo or video for social media.",
    "Never have I ever witnessed a tornado.",
    "Never have I ever attended a video call for work from an unexpected location.",
    "Never have I ever been in a soccer of football World Cup match.",
    "Never have I ever watched a horror movie after midnight, by myself.",
    "Never have I ever got blacked-out-drunk but staying “awake”, to then see videos of myself the next day of things I did unknowingly.",
    "Never have I ever learned a new skill during the pandemic.",
    "Never have I ever got lost in the woods.",
    "Never have I ever been left at the altar.",
    "Never have I ever considered writing my own book.",
    "Never have I ever been ghosted by someone I really liked.",
    "Never have I ever seen a car accident happen in front of me.",
    "Never have I ever spoken to a celebrity.",
    "Never have I ever participated in a food eating contest.",
    "Never have I ever lived (not visited) in more than 3 countries.",
    "Never have I ever sneaked into the cinema without a ticket.",
    "Never have I ever been in an ambulance.",
    "Never have I ever vomited while on an amusement park ride.",
    "Never have I ever worn the same underwear multiple days in a row.",
    "Never have I ever bought gym equipment for home, but never used it.",
    "Never have I ever seen a building collapse.",
    "Never have I ever fell asleep during a class.",
    "Never have I ever acted in a theater play.",
    "Never have I ever eaten snow.",
    "Never have I ever built a big sandcastle, to only have a wave destroy it.",
    "Never have I ever put a song on repeat for a whole day.",
    "Never have I ever swam in a salt-water pool.",
    "Never have I ever been catfished by someone.",
    "Never have I ever participated in a beauty pageant.",
    "Never have I ever bitten my own nails.",
    "Never have I ever visited multiple countries in the same day.",
    "Never have I ever been in a completely empty stadium.",
    "Never have I ever had baby vomit on me.",
    "Never have I ever spent my birthday alone.",
    "Never have I ever dropped out of a university class.",
    "Never have I ever participated in a protest.",
    "Never have I ever cried in public.",
    "Never have I ever stalked someone.",
    "Never have I ever redecorated my bedroom in the middle of the night.",
    "Never have I ever bought a very expensive gift for someone’s birthday, to only get a cheap gift back on my birthday from the same person.",
    "Never have I ever watched the same movie twice in one day.",
    "Never have I ever considered selling all my belongings and go live in a remote location.",
    "Never have I ever been in a layover inside the airport for more than 12 hours.",
    "Never have I ever gone out with my best friend’s partner behind their back.",
    "Never have I ever sleep walked.",
    "Never have I ever burned through my savings account.",
    "Never have I ever gone fishing.",
    "Never have I ever tripped and fell in public.",
    "Never have I ever eaten sand.",
    "Never have I ever learned to play a musical instrument.",
    "Never have I ever been put in the friendzone.",
    "Never have I ever helped a complete stranger.",
    "Never have I ever laughed so hard in public, making people look at me.",
    "Never have I ever fell asleep on the toilet seat at work.",
    "Never have I ever been featured on the news.",
    "Never have I ever won a scholarship.",
    "Never have I ever hit a friend in the face.",
    "Never have I ever ripped my swimming suit by accident.",
    "Never have I ever caused a birthday cake to fall on the floor.",
    "Never have I ever acted as an extra in a movie, tv show or music video.",
    "Never have I ever got married more than once.",
    "Never have I ever bought expensive tools and equipment for a completely new hobby, only to then drop it off a few days later.",
    "Never have I ever eaten my own snot.",
    "Never have I ever been dumped on an anniversary.",
    "Never have I ever taught a class.",
    "Never have I ever prepared a midnight “snack” so elaborated that I ended up cooking a whole meal.",
    "Never have I ever refused to accept a gift.",
    "Never have I ever recorded myself crying.",
    "Never have I ever fell asleep during a date.",
    "Never have I ever walked in on someone in a public bathroom.",
    "Never have I ever been to a str!p club.",
    "Never have I ever seen a dead body.",
    "Never have I ever taken pictures of meals before eating.",
    "Never have I ever pretended to be someone I’m not.",
    "Never have I ever been in the ICU.",
    "Never have I ever sniffed a flower and put it in my hair.",
    "Never have I ever kissed someone you know.",
    "Never have I ever played 'Never Have I Ever.'",
    "Never have I ever stolen something from someone close to me.",
    "Never have I ever eaten food from the garbage.",
    "Never have I ever received a traffic violation.",
    "Never have I ever snooped through a family member’s or friend’s belongings without them knowing.",
    "Never have I ever walked over five miles.",
    "Never have I ever snuck into the movie theatre without getting caught.",
    "Never have I ever picked up a hitchhiker.",
    "Never have I ever had a crush on a best friend’s sibling.",
    "Never have I ever got into a physical altercation with a good friend.",
    "Never have I ever lied to get out of going to work.",
    "Never have I ever looked through someone’s phone without their permission.",
    "Never have I ever performed on stage.",
    "Never have I ever taken money that didn’t belong to me.",
    "Never have I ever told a friend a lie to get out of hanging out with them.",
    "Never have I ever stayed up for 48 hours straight.",
    "Never have I ever visited another country.",
    "Never have I ever been suspended from school.",
    "Never have I ever pretended I had a phone call to get out of talking with someone.",
    "Never have I ever thrown up in a public setting.",
    "Never have I ever ditched out on paying the bill at a restaurant.",
    "Never have I ever tried cutting my own hair.",
    "Never have I ever given someone a black eye.",
    "Never have I ever made money from performing on the streets.",
    "Never have I ever told someone that I loved them without actually meaning it.",
    "Never have I ever embarrassed myself trying to look cool in front of someone I liked.",
    "Never have I ever gone fishing on a boat in the lake.",
    "Never have I ever taken a ride on a train.",
    "Never have I ever gotten a tattoo that I later regretted.",
    "Never have I ever thrown my own surprise party.",
    "Never have I ever cheated on an important test in school.",
    "Never have I ever dated someone because I was bored.",
    "Never have I ever got bitten by a snake.",
    "Never have I ever thrown something at mine or someone else’s television.",
    "Never have I ever went to the hospital for something embarrassing.",
    "Never have I ever paid for something in all pennies.",
    "Never have I ever been fired from a job.",
    "Never have I ever shot a gun.",
    "Never have I ever been to a Broadway play.",
    "Never have I ever had a job that I absolutely despised.",
    "Never have I ever starred in an embarrassing video that is now on the internet.",
    "Never have I ever walked barefoot outside farther than my backyard.",
    "Never have I ever taken the blame for something I’ve never done.",
    "Never have I ever went camping without an RV.",
    "Never have I ever seen or felt a ghost.",
    "Never have I ever fallen in love with someone that didn’t know I existed.",
    "Never have I ever broken a bone.",
    "Never have I ever taken my parent’s car for a joy ride without them knowing.",
    "Never have I ever been part of a talent show.",
    "Never have I ever cried in front of a crush.",
    "Never have I ever ate a whole carton of ice cream in one sitting by myself.",
    "Never have I ever dyed my hair.",
    "Never have I ever cheated on a test.",
    "Never have I ever fallen in love at the first sight.",
    "Never have I ever had a friends with benefits.",
    "Never have I ever had a one night stand.",
    "Never have I ever bragged about something I have not done.",
    "Never have I ever experimented to see my sexual orientation.",
    "Never have I ever said ‘I love you’ just to get laid.",
    "Never have I ever spied on my neighbours.",
    "Never have I ever doubted my heterosexuality.",
    "Never have I ever made fun of someone.",
    "Never have I ever watched keeping up with the Kardashians.",
    "Never have I ever stole something with a higher value than $10.",
    "Never have I ever really liked a song by Justin Bieber.",
    "Never have I ever bet on something.",
    "Never have I ever done a handstand with one hand.",
    "Never have I ever stalked an ex’s boyfriend or girlfriend on social media.",
    "Never have I ever lied to a friend to avoid a greater evil.",
    "Never have I ever escaped from class.",
    "Never have I ever had an open relationship.",
    "Never have I ever cheated on a test.",
    "Never have I ever grabbed the wrong person’s hand.",
    "Never have I ever fallen in love with anyone through a social network.",
    "Never have I ever lied in this game.",
    "Never have I ever said an “I love you” without feeling it.",
    "Never have I ever been kicked out of a bar.",
    "Never have I ever logged into Facebook while drunk.",
    "Never have I ever stuck gum under a desk.",
    "Never have I ever bit my tongue.",
    "Never have I ever stop remembering my first love.",
    "Never have I ever done pictures in underwear.",
    "Never have I ever refused a kiss.",
    "Never have I ever been unfaithful.",
    "Never have I ever lied to my parents about being hungover.",
    "Never have I ever gone to the bathroom and then not wash my hands.",
    "Never have I ever kissed someone of the same gender.",
    "Never have I ever swam nakd in a pool / beach.",
    "Never have I ever woken up drunk the next day.",
    "Never have I ever got drunk.",
    "Never have I ever kissed my best friend.",
    "Never have I ever smoked.",
    "Never have I ever eaten food that fell on the floor.",
    "Never have I ever got drunk playing never have I ever.",
    "Never have I ever screwed up at school.",
    "Never have I ever been with the former love of my best friend.",
    "Never have I ever seen a top less on the beach.",
    "Never have I ever had a friend with benefits.",
    "Never have I ever fought in the street.",
    "Never have I ever fallen asleep on the bus and I’ve passed my station.",
    "Never have I ever been in love with my teacher in college.",
    "Never have I ever been robbed.",
    "Never have I ever received a serenade.",
    "Never have I ever sneaked into a party.",
    "Never have I ever wanted to fall in love with my sister’s/brothers friend.",
    "Never have I ever made love with someone from the university.",
    "Never have I ever been stuck in a lift.",
    "Never have I ever Illegally taken something across the border.",
    "Never have I ever lied to my parents about where I’m going.",
    "Never have I ever finished an entire jawbreaker.",
    "Never have I ever been in handcuffs.",
    "Never have I ever fallen asleep in the cinema.",
    "Never have I ever done something I regret.",
    "Never have I ever picked my nose in public.",
    "Never have I ever taken part in a talent show."
];
